trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:
  - stage: CI
    displayName: 'Integración Continua'
    jobs:
      - job: BuildJob
        steps:
          - script: dotnet restore MiApi.sln
          - script: dotnet build MiApi.sln --configuration $(buildConfiguration) --no-restore
            displayName: 'Compilar aplicación'

  - stage: Testing
    displayName: 'Pruebas Unitarias'
    dependsOn: CI
    jobs:
      - job: TestJob
        steps:
          - script: dotnet test tests/MiApi.Tests/MiApi.Tests.csproj --configuration $(buildConfiguration)
            displayName: 'Ejecutar pruebas unitarias'

  - stage: Delivery
    displayName: 'Construcción y Despliegue'
    dependsOn: Testing
    jobs:
      - job: DockerBuildAndDeploy
        steps:
          # 1. Construir y subir imagen al registro (ACR)
          - task: Docker@2
            displayName: 'Build and Push'
            inputs:
              containerRegistry: 'ACR-Conexion'
              repository: $(imageName)
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(Build.BuildId)
                latest

          # 2. Desplegar en Azure App Service usando la imagen recién creada
          - task: AzureWebAppContainer@1
            displayName: 'Desplegar en Azure'
            inputs:
              azureSubscription: 'Azure-Conexion'
              appName: $(webAppName)
              containers: $(azureContainerRegistry)/$(imageName):latest
              # Inyección segura de la cadena de conexión
              appSettings: '-ConnectionStrings__DefaultConnection "$(DB_CONNECTION_STRING)"'