services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-CU23-ubuntu-22.04
    container_name: sqlserver
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  mi-api:
    build: .
    container_name: miapi
    restart: always
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MiApiDB;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
    depends_on:
      - sqlserver
    volumes:
      - ./logs:/app/logs

volumes:
  sqlserver_data: